services:
    ex_youtube.job_executor:
        class: Keboola\YoutubeExtractorBundle\Job\Executor
        arguments: ['@keboola_extractor.configuration', '@ex_youtube.extractor', '@logger', '@syrup.temp', '@syrup.encryptor']
    ex_youtube.extractor:
        class: Keboola\YoutubeExtractorBundle\YoutubeExtractor
        arguments: ['%youtube%']
    keboola_extractor.configuration:
        class: Keboola\ExtractorBundle\Common\Configuration
        arguments: ['%app_name%', '@syrup.temp']
parameters: null
